/*
 * Sample 物件サンプルデータ
 * ※実データではありません。運用時はこの配列を実際の物件情報に差し替えてください。
 */
const PROPERTY_TYPES = {
  "new-house": "新築戸建",
  "used-house": "中古戸建",
  mansion: "マンション",
  land: "土地",
};

const PROPERTIES = [
  {
    id: 1,
    type: "new-house",
    isNew: true,
    title: "岡山市北区 新築一戸建て 全4棟",
    price: 3480,
    area: "岡山市北区",
    address: "岡山県岡山市北区大安寺（プレースホルダー住所）",
    layout: "4LDK",
    size: 105.2,
    landSize: 132.4,
    age: "新築",
    station: "JR大安寺駅 徒歩12分",
    image: "images/property-1.svg",
    features: ["耐震等級3", "全館床暖房", "太陽光パネル", "カースペース2台"],
    description:
      "閑静な住宅街に建つ全4棟の新築分譲住宅。子育て世代に人気の学区内で、収納力の高い4LDKプランです。標準仕様で耐震・断熱性能にこだわりました。",
  },
  {
    id: 2,
    type: "mansion",
    isNew: true,
    title: "岡山駅前 タワーマンション 12階部分",
    price: 4280,
    area: "岡山市北区",
    address: "岡山県岡山市北区駅元町（プレースホルダー住所）",
    layout: "3LDK",
    size: 78.5,
    landSize: null,
    age: "築3年",
    station: "JR岡山駅 徒歩6分",
    image: "images/property-2.svg",
    features: ["オートロック", "宅配ボックス", "駅近", "眺望良好"],
    description:
      "岡山駅直結エリアの人気タワーマンション。高層階からの眺望が魅力で、日々の買い物や通勤に便利な立地です。",
  },
  {
    id: 3,
    type: "used-house",
    isNew: false,
    title: "倉敷市中庄 中古戸建て リフォーム済",
    price: 1980,
    area: "倉敷市",
    address: "岡山県倉敷市中庄（プレースホルダー住所）",
    layout: "4LDK",
    size: 98.7,
    landSize: 158.0,
    age: "築18年",
    station: "JR中庄駅 徒歩9分",
    image: "images/property-3.svg",
    features: ["水回りリフォーム済", "駐車場2台", "庭付き", "南向き"],
    description:
      "水回りをリフォーム済みの築18年戸建て。広めの庭付きで、ペットを飼われているご家庭にもおすすめです。",
  },
  {
    id: 4,
    type: "land",
    isNew: false,
    title: "総社市 分譲土地 全6区画",
    price: 890,
    area: "総社市",
    address: "岡山県総社市駅前（プレースホルダー住所）",
    layout: "-",
    size: null,
    landSize: 145.6,
    age: "-",
    station: "JR総社駅 徒歩15分",
    image: "images/property-4.svg",
    features: ["建築条件なし", "上下水道完備", "整形地", "全区画南向き"],
    description:
      "建築条件なしでご希望のハウスメーカーで自由に家づくりができる分譲地です。上下水道・都市ガスが整備済みです。",
  },
  {
    id: 5,
    type: "used-house",
    isNew: false,
    title: "岡山市中区 中古戸建て 5LDK",
    price: 2580,
    area: "岡山市中区",
    address: "岡山県岡山市中区長岡（プレースホルダー住所）",
    layout: "5LDK",
    size: 121.3,
    landSize: 175.8,
    age: "築12年",
    station: "JR高島駅 徒歩14分",
    image: "images/property-5.svg",
    features: ["二世帯対応", "駐車場3台", "太陽光パネル", "追い焚き機能"],
    description:
      "二世帯同居にも対応できるゆとりの5LDK。駐車場3台分を確保しており、車を複数台お持ちのご家庭にも安心です。",
  },
  {
    id: 6,
    type: "mansion",
    isNew: false,
    title: "岡山市南区 中古マンション 角部屋",
    price: 1680,
    area: "岡山市南区",
    address: "岡山県岡山市南区築港元町（プレースホルダー住所）",
    layout: "3LDK",
    size: 72.1,
    landSize: null,
    age: "築15年",
    station: "JR大元駅 徒歩7分",
    image: "images/property-6.svg",
    features: ["角部屋", "2面採光", "管理体制良好", "ペット相談可"],
    description:
      "2面採光の明るい角部屋タイプ。管理体制が良好で、資産価値を維持しやすいマンションです。",
  },
  {
    id: 7,
    type: "new-house",
    isNew: true,
    title: "早島町 新築一戸建て 全2棟",
    price: 3180,
    area: "都窪郡早島町",
    address: "岡山県都窪郡早島町（プレースホルダー住所）",
    layout: "3LDK",
    size: 92.4,
    landSize: 140.2,
    age: "新築",
    station: "JR早島駅 徒歩10分",
    image: "images/property-7.svg",
    features: ["ZEH仕様", "全室収納", "食洗機標準装備", "対面キッチン"],
    description:
      "岡山・倉敷どちらへのアクセスも良好な早島エリアの新築住宅。ZEH仕様で光熱費を抑えられます。",
  },
  {
    id: 8,
    type: "land",
    isNew: false,
    title: "岡山市北区 売地 商業施設近接",
    price: 1250,
    area: "岡山市北区",
    address: "岡山県岡山市北区西長瀬（プレースホルダー住所）",
    layout: "-",
    size: null,
    landSize: 168.3,
    age: "-",
    station: "JR大元駅 徒歩18分",
    image: "images/property-8.svg",
    features: ["商業施設徒歩圏", "整形地", "角地", "建築条件なし"],
    description:
      "スーパーや商業施設が徒歩圏内にある生活至便な売地です。角地で開放感のある土地形状です。",
  },
];
